name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  DUCKDB_VERSION: "1.4.1"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / AR ${{ matrix.activerecord }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3"
          - "3.4"
        activerecord:
          - "8.0"
          - "8.1"
    env:
      ACTIVERECORD_VERSION: ${{ matrix.activerecord }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup DuckDB
        uses: ./.github/actions/setup-duckdb
        with:
          version: ${{ env.DUCKDB_VERSION }}
          arch: amd64
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop
